# {{title}}

> {{tagline}}

## 🎯 {{key_metric}}

{{cover_image_block}}

## Overview 概要

{{overview}}

## Problem 何を解決するか

{{problem_bullets}}

## Solution どうやって解決するか

{{solution}}

## Features 主な機能

{{features_bullets}}

## Tech Stack 使用技術

{{tech_stack_table}}

{{demo_section}}

## 📊 Results 成果

{{results}}

## 👥 対象・役割

{{target_role}}

---

## 📝 このリポジトリについて

このリポジトリは **ポートフォリオ公開用** に自動生成されたものです。

- **原本は別途 Private リポジトリで管理**されており、このリポジトリは原本のサニタイズ済み複製です
- メールアドレス・APIキー・プライベート ID 等の機密情報は自動的に `<...>` プレースホルダに置換されています
- 定期実行される自動化ツール `portfolio-publish-tool` により公開されました

## License

{{license}}

---

*Published: {{published_at}} / Generated by [portfolio-publish-tool](https://github.com/<github-owner>/portfolio-publish-tool)*
